language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: DbveaxDMtEP+/Er6ktKCP+P42uDU8xXWRBlVGaqVNU3muaRmmZtj8ngAARxfzY0f9amlJlCavqkEIAumQl9BYKPWIra28ylsLNbzAoCIi8alf9WLgddKwVWsTcZo9+UYocuY6UivJVkofycfFJ1blw/83dWMG0/TiW6s/SrwoDw=
script:
- "./gradle_init.sh"
- gradle assemble
- "./gradle_clean.sh"
- ant
- bin/start.sh
install: true
after_success:
- sh .utility/push-javadoc-to-gh-pages.sh
deploy:
  provider: heroku
  email: sudheesh95@gmail.com
  strategy: git
  buildpack: https://github.com/loklak/heroku_buildpack_ant_loklak
  api_key:
  - secure: zE6ZJhHC2qq/TtVti46V5C5ZWphmAuq2A/+IenONCW4zNqO96jk1tno0cclGb8k7FO9ZFpF7oSoKWs8oYo5D3oYmSiWhEd02orwW6GT/HHWSd3J84Bue0zxkQxguMt4/dQ6DIroVcpbvP9+Xdg8mLJEm8IG2Xs58gsDK4U3RDro=
  app: loklak-server-dev
  on:
    branch: development
