language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: DbveaxDMtEP+/Er6ktKCP+P42uDU8xXWRBlVGaqVNU3muaRmmZtj8ngAARxfzY0f9amlJlCavqkEIAumQl9BYKPWIra28ylsLNbzAoCIi8alf9WLgddKwVWsTcZo9+UYocuY6UivJVkofycfFJ1blw/83dWMG0/TiW6s/SrwoDw=
script:
- "./gradle_init.sh"
- gradle assemble
- "./gradle_clean.sh"
- ant
- bin/start.sh
install: true
after_success:
- sh .utility/push-javadoc-to-gh-pages.sh
deploy:
  provider: heroku
  buildpack: https://github.com/loklak/heroku_buildpack_ant_loklak
  api_key:
    secure: WaSsrudDpmwZrVQRbshEVoGHWBMGieUKU+qYaiGvcrbaK18uvOcGv8uNdb4nz9KOBu0tv7XZL1Oi0WjQsUYloyGIMSdTtx2RCq+qIvgLwCvef5iV+qi8hq+rrAliSiPpAFEdNllFYKTPIP3Qh6GySvrFd+5HcE4/aKzzK3pUpmo=
  app: loklak_server_dev
  on:
    repo: sudheesh001/loklak_server
