language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: DbveaxDMtEP+/Er6ktKCP+P42uDU8xXWRBlVGaqVNU3muaRmmZtj8ngAARxfzY0f9amlJlCavqkEIAumQl9BYKPWIra28ylsLNbzAoCIi8alf9WLgddKwVWsTcZo9+UYocuY6UivJVkofycfFJ1blw/83dWMG0/TiW6s/SrwoDw=
script:
- "./gradle_init.sh"
- gradle assemble
- "./gradle_clean.sh"
- ant
- bin/start.sh
install: true
after_success:
- sh .utility/push-javadoc-to-gh-pages.sh
deploy:
  provider: heroku
  strategy: git
  buildpack: https://github.com/loklak/heroku_buildpack_ant_loklak
  api_key:
    secure: u/IiBmqO3zmHCLKpp7rtgDAYA6OO1Fma9xONZ6LStQ1wmCg7KvYwn/66OLmulrXy56K5UNRmVgxbkZyywxwmIS0199Gw/l4iUHfNz1gOlnV0CoaaBAQxJBGHwZPrQQvnefDDeIs8WwW3y62kX8w26dR2y0EwAH4pANMiu7Jkbt4=
  app: loklak-server-dev
  on:
    branch: development
