language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: DbveaxDMtEP+/Er6ktKCP+P42uDU8xXWRBlVGaqVNU3muaRmmZtj8ngAARxfzY0f9amlJlCavqkEIAumQl9BYKPWIra28ylsLNbzAoCIi8alf9WLgddKwVWsTcZo9+UYocuY6UivJVkofycfFJ1blw/83dWMG0/TiW6s/SrwoDw=
script:
- "./gradle_init.sh"
- gradle assemble
- "./gradle_clean.sh"
- ant
- bin/start.sh
install: true
after_success:
- sh .utility/push-javadoc-to-gh-pages.sh
deploy:
  provider: heroku
  api_key:
    secure: WPXU9RmEVvk0Gv7qsOFVrGtH+nxB+Y75M7VJ/9QvH3fqF+SS04Mw2OGwNBKogukLbCPqCCRveXinJHFsn44NKOzH1WBYgNOzLHY0Ceqz8MnZQLjcmE+vi/u1nkwwZRmwGRH2LTO9/07eEAq4D2hRp3weoWGVxwc+/JqiakH6pyU=
  app: loklak-server-dev
  on:
    branch: development
