version: '2'

services:
         loklak:
                build: .
         ports:
             - "80:80"
         #Map volume-folder    
         volumes:
             - data:/data
             
#Create named volume             
volumes:
       data: 
           external: false
